package com.woniu.dao;

import com.woniu.domain.Certification;
import com.woniu.domain.CertificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CertificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int countByExample(CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByExample(CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByPrimaryKey(Integer certificationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insert(Certification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insertSelective(Certification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    List<Certification> selectByExample(CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    Certification selectByPrimaryKey(Integer certificationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Certification record, @Param("example") CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExample(@Param("record") Certification record, @Param("example") CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKeySelective(Certification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKey(Certification record);
}