package com.woniu.dao;

import com.woniu.domain.Debtinvest;
import com.woniu.domain.DebtinvestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DebtinvestMapper {
	
	List<Debtinvest> findByLoanapply(Integer userinfoid);
	
	List<Debtinvest> findByDebttransfer(Integer userinfoid);
	
	List<Debtinvest> selectByExample(DebtinvestExample example,RowBounds rowBounds);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debtinvest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int countByExample(DebtinvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debtinvest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByExample(DebtinvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debtinvest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByPrimaryKey(Integer debtinvestid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debtinvest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insert(Debtinvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debtinvest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insertSelective(Debtinvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debtinvest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    List<Debtinvest> selectByExample(DebtinvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debtinvest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    Debtinvest selectByPrimaryKey(Integer debtinvestid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debtinvest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Debtinvest record, @Param("example") DebtinvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debtinvest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExample(@Param("record") Debtinvest record, @Param("example") DebtinvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debtinvest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKeySelective(Debtinvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debtinvest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKey(Debtinvest record);
}