package com.woniu.dao;

import com.woniu.domain.Debttransferapply;
import com.woniu.domain.DebttransferapplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DebttransferapplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debttransferapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int countByExample(DebttransferapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debttransferapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByExample(DebttransferapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debttransferapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByPrimaryKey(Integer debttransferapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debttransferapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insert(Debttransferapply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debttransferapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insertSelective(Debttransferapply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debttransferapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    List<Debttransferapply> selectByExample(DebttransferapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debttransferapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    Debttransferapply selectByPrimaryKey(Integer debttransferapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debttransferapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Debttransferapply record, @Param("example") DebttransferapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debttransferapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExample(@Param("record") Debttransferapply record, @Param("example") DebttransferapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debttransferapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKeySelective(Debttransferapply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debttransferapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKey(Debttransferapply record);
}