package com.woniu.dao;

import com.woniu.domain.Invest;
import com.woniu.domain.InvestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InvestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int countByExample(InvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByExample(InvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByPrimaryKey(Integer investid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insert(Invest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insertSelective(Invest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    List<Invest> selectByExample(InvestExample example,RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    Invest selectByPrimaryKey(Integer investid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Invest record, @Param("example") InvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExample(@Param("record") Invest record, @Param("example") InvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKeySelective(Invest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKey(Invest record);

	List<Invest> selectByExample(InvestExample example);
}