package com.woniu.dao;

import com.woniu.domain.Loanrate;
import com.woniu.domain.LoanrateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoanrateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int countByExample(LoanrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByExample(LoanrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByPrimaryKey(Integer loanrateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insert(Loanrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insertSelective(Loanrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    List<Loanrate> selectByExample(LoanrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    Loanrate selectByPrimaryKey(Integer loanrateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Loanrate record, @Param("example") LoanrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExample(@Param("record") Loanrate record, @Param("example") LoanrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKeySelective(Loanrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKey(Loanrate record);
}