package com.woniu.dao;

import com.woniu.domain.Loantime;
import com.woniu.domain.LoantimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoantimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loantime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int countByExample(LoantimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loantime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByExample(LoantimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loantime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByPrimaryKey(Integer loantimeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loantime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insert(Loantime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loantime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insertSelective(Loantime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loantime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    List<Loantime> selectByExample(LoantimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loantime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    Loantime selectByPrimaryKey(Integer loantimeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loantime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Loantime record, @Param("example") LoantimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loantime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExample(@Param("record") Loantime record, @Param("example") LoantimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loantime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKeySelective(Loantime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loantime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKey(Loantime record);
}