package com.woniu.dao;

import com.woniu.domain.Loandisplay;
import com.woniu.domain.LoandisplayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoandisplayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loandisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int countByExample(LoandisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loandisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByExample(LoandisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loandisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByPrimaryKey(Integer loandisplayid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loandisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insert(Loandisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loandisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insertSelective(Loandisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loandisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    List<Loandisplay> selectByExample(LoandisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loandisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    Loandisplay selectByPrimaryKey(Integer loandisplayid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loandisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Loandisplay record, @Param("example") LoandisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loandisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExample(@Param("record") Loandisplay record, @Param("example") LoandisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loandisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKeySelective(Loandisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loandisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKey(Loandisplay record);
}