package com.woniu.dao;

import com.woniu.domain.RechargeWithdraw;
import com.woniu.domain.RechargeWithdrawExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RechargeWithdrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int countByExample(RechargeWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByExample(RechargeWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByPrimaryKey(Integer rechargeWithdrawId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insert(RechargeWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insertSelective(RechargeWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    List<RechargeWithdraw> selectByExample(RechargeWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    RechargeWithdraw selectByPrimaryKey(Integer rechargeWithdrawId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") RechargeWithdraw record, @Param("example") RechargeWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExample(@Param("record") RechargeWithdraw record, @Param("example") RechargeWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKeySelective(RechargeWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKey(RechargeWithdraw record);
}