package com.woniu.dao;

import com.woniu.domain.Systemlog;
import com.woniu.domain.SystemlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int countByExample(SystemlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByExample(SystemlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByPrimaryKey(Integer systemlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insert(Systemlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insertSelective(Systemlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    List<Systemlog> selectByExample(SystemlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    Systemlog selectByPrimaryKey(Integer systemlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Systemlog record, @Param("example") SystemlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExample(@Param("record") Systemlog record, @Param("example") SystemlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKeySelective(Systemlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKey(Systemlog record);
}