package com.woniu.dao;

import com.woniu.domain.Transactionlog;
import com.woniu.domain.TransactionlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int countByExample(TransactionlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByExample(TransactionlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int deleteByPrimaryKey(Integer transactionlog);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insert(Transactionlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int insertSelective(Transactionlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    List<Transactionlog> selectByExample(TransactionlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    Transactionlog selectByPrimaryKey(Integer transactionlog);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Transactionlog record, @Param("example") TransactionlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByExample(@Param("record") Transactionlog record, @Param("example") TransactionlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKeySelective(Transactionlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    int updateByPrimaryKey(Transactionlog record);
}