package com.woniu.domain;

public class Bankcard {
	
    @Override
	public String toString() {
		return "Bankcard [bankcardid=" + bankcardid + ", bankcardnum=" + bankcardnum + ", bankcardname=" + bankcardname
				+ ", walletid=" + walletid + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.bankcardid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer bankcardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.bankcardnum
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String bankcardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.bankcardname
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String bankcardname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.walletid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer walletid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.bankcardid
     *
     * @return the value of bankcard.bankcardid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getBankcardid() {
        return bankcardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.bankcardid
     *
     * @param bankcardid the value for bankcard.bankcardid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setBankcardid(Integer bankcardid) {
        this.bankcardid = bankcardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.bankcardnum
     *
     * @return the value of bankcard.bankcardnum
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getBankcardnum() {
        return bankcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.bankcardnum
     *
     * @param bankcardnum the value for bankcard.bankcardnum
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setBankcardnum(String bankcardnum) {
        this.bankcardnum = bankcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.bankcardname
     *
     * @return the value of bankcard.bankcardname
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getBankcardname() {
        return bankcardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.bankcardname
     *
     * @param bankcardname the value for bankcard.bankcardname
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setBankcardname(String bankcardname) {
        this.bankcardname = bankcardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.walletid
     *
     * @return the value of bankcard.walletid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getWalletid() {
        return walletid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.walletid
     *
     * @param walletid the value for bankcard.walletid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setWalletid(Integer walletid) {
        this.walletid = walletid;
    }
}