package com.woniu.domain;

import java.util.ArrayList;
import java.util.List;

public class BankcardExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public BankcardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBankcardidIsNull() {
            addCriterion("bankcardid is null");
            return (Criteria) this;
        }

        public Criteria andBankcardidIsNotNull() {
            addCriterion("bankcardid is not null");
            return (Criteria) this;
        }

        public Criteria andBankcardidEqualTo(Integer value) {
            addCriterion("bankcardid =", value, "bankcardid");
            return (Criteria) this;
        }

        public Criteria andBankcardidNotEqualTo(Integer value) {
            addCriterion("bankcardid <>", value, "bankcardid");
            return (Criteria) this;
        }

        public Criteria andBankcardidGreaterThan(Integer value) {
            addCriterion("bankcardid >", value, "bankcardid");
            return (Criteria) this;
        }

        public Criteria andBankcardidGreaterThanOrEqualTo(Integer value) {
            addCriterion("bankcardid >=", value, "bankcardid");
            return (Criteria) this;
        }

        public Criteria andBankcardidLessThan(Integer value) {
            addCriterion("bankcardid <", value, "bankcardid");
            return (Criteria) this;
        }

        public Criteria andBankcardidLessThanOrEqualTo(Integer value) {
            addCriterion("bankcardid <=", value, "bankcardid");
            return (Criteria) this;
        }

        public Criteria andBankcardidIn(List<Integer> values) {
            addCriterion("bankcardid in", values, "bankcardid");
            return (Criteria) this;
        }

        public Criteria andBankcardidNotIn(List<Integer> values) {
            addCriterion("bankcardid not in", values, "bankcardid");
            return (Criteria) this;
        }

        public Criteria andBankcardidBetween(Integer value1, Integer value2) {
            addCriterion("bankcardid between", value1, value2, "bankcardid");
            return (Criteria) this;
        }

        public Criteria andBankcardidNotBetween(Integer value1, Integer value2) {
            addCriterion("bankcardid not between", value1, value2, "bankcardid");
            return (Criteria) this;
        }

        public Criteria andBankcardnumIsNull() {
            addCriterion("bankcardnum is null");
            return (Criteria) this;
        }

        public Criteria andBankcardnumIsNotNull() {
            addCriterion("bankcardnum is not null");
            return (Criteria) this;
        }

        public Criteria andBankcardnumEqualTo(String value) {
            addCriterion("bankcardnum =", value, "bankcardnum");
            return (Criteria) this;
        }

        public Criteria andBankcardnumNotEqualTo(String value) {
            addCriterion("bankcardnum <>", value, "bankcardnum");
            return (Criteria) this;
        }

        public Criteria andBankcardnumGreaterThan(String value) {
            addCriterion("bankcardnum >", value, "bankcardnum");
            return (Criteria) this;
        }

        public Criteria andBankcardnumGreaterThanOrEqualTo(String value) {
            addCriterion("bankcardnum >=", value, "bankcardnum");
            return (Criteria) this;
        }

        public Criteria andBankcardnumLessThan(String value) {
            addCriterion("bankcardnum <", value, "bankcardnum");
            return (Criteria) this;
        }

        public Criteria andBankcardnumLessThanOrEqualTo(String value) {
            addCriterion("bankcardnum <=", value, "bankcardnum");
            return (Criteria) this;
        }

        public Criteria andBankcardnumLike(String value) {
            addCriterion("bankcardnum like", value, "bankcardnum");
            return (Criteria) this;
        }

        public Criteria andBankcardnumNotLike(String value) {
            addCriterion("bankcardnum not like", value, "bankcardnum");
            return (Criteria) this;
        }

        public Criteria andBankcardnumIn(List<String> values) {
            addCriterion("bankcardnum in", values, "bankcardnum");
            return (Criteria) this;
        }

        public Criteria andBankcardnumNotIn(List<String> values) {
            addCriterion("bankcardnum not in", values, "bankcardnum");
            return (Criteria) this;
        }

        public Criteria andBankcardnumBetween(String value1, String value2) {
            addCriterion("bankcardnum between", value1, value2, "bankcardnum");
            return (Criteria) this;
        }

        public Criteria andBankcardnumNotBetween(String value1, String value2) {
            addCriterion("bankcardnum not between", value1, value2, "bankcardnum");
            return (Criteria) this;
        }

        public Criteria andBankcardnameIsNull() {
            addCriterion("bankcardname is null");
            return (Criteria) this;
        }

        public Criteria andBankcardnameIsNotNull() {
            addCriterion("bankcardname is not null");
            return (Criteria) this;
        }

        public Criteria andBankcardnameEqualTo(String value) {
            addCriterion("bankcardname =", value, "bankcardname");
            return (Criteria) this;
        }

        public Criteria andBankcardnameNotEqualTo(String value) {
            addCriterion("bankcardname <>", value, "bankcardname");
            return (Criteria) this;
        }

        public Criteria andBankcardnameGreaterThan(String value) {
            addCriterion("bankcardname >", value, "bankcardname");
            return (Criteria) this;
        }

        public Criteria andBankcardnameGreaterThanOrEqualTo(String value) {
            addCriterion("bankcardname >=", value, "bankcardname");
            return (Criteria) this;
        }

        public Criteria andBankcardnameLessThan(String value) {
            addCriterion("bankcardname <", value, "bankcardname");
            return (Criteria) this;
        }

        public Criteria andBankcardnameLessThanOrEqualTo(String value) {
            addCriterion("bankcardname <=", value, "bankcardname");
            return (Criteria) this;
        }

        public Criteria andBankcardnameLike(String value) {
            addCriterion("bankcardname like", value, "bankcardname");
            return (Criteria) this;
        }

        public Criteria andBankcardnameNotLike(String value) {
            addCriterion("bankcardname not like", value, "bankcardname");
            return (Criteria) this;
        }

        public Criteria andBankcardnameIn(List<String> values) {
            addCriterion("bankcardname in", values, "bankcardname");
            return (Criteria) this;
        }

        public Criteria andBankcardnameNotIn(List<String> values) {
            addCriterion("bankcardname not in", values, "bankcardname");
            return (Criteria) this;
        }

        public Criteria andBankcardnameBetween(String value1, String value2) {
            addCriterion("bankcardname between", value1, value2, "bankcardname");
            return (Criteria) this;
        }

        public Criteria andBankcardnameNotBetween(String value1, String value2) {
            addCriterion("bankcardname not between", value1, value2, "bankcardname");
            return (Criteria) this;
        }

        public Criteria andWalletidIsNull() {
            addCriterion("walletid is null");
            return (Criteria) this;
        }

        public Criteria andWalletidIsNotNull() {
            addCriterion("walletid is not null");
            return (Criteria) this;
        }

        public Criteria andWalletidEqualTo(Integer value) {
            addCriterion("walletid =", value, "walletid");
            return (Criteria) this;
        }

        public Criteria andWalletidNotEqualTo(Integer value) {
            addCriterion("walletid <>", value, "walletid");
            return (Criteria) this;
        }

        public Criteria andWalletidGreaterThan(Integer value) {
            addCriterion("walletid >", value, "walletid");
            return (Criteria) this;
        }

        public Criteria andWalletidGreaterThanOrEqualTo(Integer value) {
            addCriterion("walletid >=", value, "walletid");
            return (Criteria) this;
        }

        public Criteria andWalletidLessThan(Integer value) {
            addCriterion("walletid <", value, "walletid");
            return (Criteria) this;
        }

        public Criteria andWalletidLessThanOrEqualTo(Integer value) {
            addCriterion("walletid <=", value, "walletid");
            return (Criteria) this;
        }

        public Criteria andWalletidIn(List<Integer> values) {
            addCriterion("walletid in", values, "walletid");
            return (Criteria) this;
        }

        public Criteria andWalletidNotIn(List<Integer> values) {
            addCriterion("walletid not in", values, "walletid");
            return (Criteria) this;
        }

        public Criteria andWalletidBetween(Integer value1, Integer value2) {
            addCriterion("walletid between", value1, value2, "walletid");
            return (Criteria) this;
        }

        public Criteria andWalletidNotBetween(Integer value1, Integer value2) {
            addCriterion("walletid not between", value1, value2, "walletid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bankcard
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 15:11:02 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bankcard
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}