package com.woniu.domain;

public class Certification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certification.certificationid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer certificationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certification.idcardnum
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String idcardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certification.idcardimgfront
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String idcardimgfront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certification.idcardimgback
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String idcardimgback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certification.idcardimghand
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String idcardimghand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certification.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer userinfoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certification.certificationid
     *
     * @return the value of certification.certificationid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getCertificationid() {
        return certificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certification.certificationid
     *
     * @param certificationid the value for certification.certificationid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setCertificationid(Integer certificationid) {
        this.certificationid = certificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certification.idcardnum
     *
     * @return the value of certification.idcardnum
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getIdcardnum() {
        return idcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certification.idcardnum
     *
     * @param idcardnum the value for certification.idcardnum
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setIdcardnum(String idcardnum) {
        this.idcardnum = idcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certification.idcardimgfront
     *
     * @return the value of certification.idcardimgfront
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getIdcardimgfront() {
        return idcardimgfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certification.idcardimgfront
     *
     * @param idcardimgfront the value for certification.idcardimgfront
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setIdcardimgfront(String idcardimgfront) {
        this.idcardimgfront = idcardimgfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certification.idcardimgback
     *
     * @return the value of certification.idcardimgback
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getIdcardimgback() {
        return idcardimgback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certification.idcardimgback
     *
     * @param idcardimgback the value for certification.idcardimgback
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setIdcardimgback(String idcardimgback) {
        this.idcardimgback = idcardimgback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certification.idcardimghand
     *
     * @return the value of certification.idcardimghand
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getIdcardimghand() {
        return idcardimghand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certification.idcardimghand
     *
     * @param idcardimghand the value for certification.idcardimghand
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setIdcardimghand(String idcardimghand) {
        this.idcardimghand = idcardimghand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certification.userinfoid
     *
     * @return the value of certification.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certification.userinfoid
     *
     * @param userinfoid the value for certification.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }
}