package com.woniu.domain;

public class Contact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contactid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer contactid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contactname
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String contactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contactphone
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String contactphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.relationship
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String relationship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer userinfoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contactid
     *
     * @return the value of contact.contactid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getContactid() {
        return contactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contactid
     *
     * @param contactid the value for contact.contactid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setContactid(Integer contactid) {
        this.contactid = contactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contactname
     *
     * @return the value of contact.contactname
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contactname
     *
     * @param contactname the value for contact.contactname
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setContactname(String contactname) {
        this.contactname = contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contactphone
     *
     * @return the value of contact.contactphone
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getContactphone() {
        return contactphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contactphone
     *
     * @param contactphone the value for contact.contactphone
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setContactphone(String contactphone) {
        this.contactphone = contactphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.relationship
     *
     * @return the value of contact.relationship
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.relationship
     *
     * @param relationship the value for contact.relationship
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.userinfoid
     *
     * @return the value of contact.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.userinfoid
     *
     * @param userinfoid the value for contact.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }
}