package com.woniu.domain;

import java.util.Date;

public class Debttransferapply {
	private Userinfo userinfo;
	private Servicecharge scharge;
	
	public Servicecharge getScharge() {
		return scharge;
	}

	public void setScharge(Servicecharge scharge) {
		this.scharge = scharge;
	}

	public Userinfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debttransferapply.debttransferapplyid
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    private Integer debttransferapplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debttransferapply.userinfoid
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    private Integer userinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debttransferapply.investid
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    private Integer investid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debttransferapply.applytime
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    private Date applytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debttransferapply.checked
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    private Boolean checked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debttransferapply.servicecharge
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    private Double servicecharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debttransferapply.servicechargeid
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    private Integer servicechargeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debttransferapply.ispass
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    private Boolean ispass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debttransferapply.debttransferapplyid
     *
     * @return the value of debttransferapply.debttransferapplyid
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public Integer getDebttransferapplyid() {
        return debttransferapplyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debttransferapply.debttransferapplyid
     *
     * @param debttransferapplyid the value for debttransferapply.debttransferapplyid
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public void setDebttransferapplyid(Integer debttransferapplyid) {
        this.debttransferapplyid = debttransferapplyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debttransferapply.userinfoid
     *
     * @return the value of debttransferapply.userinfoid
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debttransferapply.userinfoid
     *
     * @param userinfoid the value for debttransferapply.userinfoid
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debttransferapply.investid
     *
     * @return the value of debttransferapply.investid
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public Integer getInvestid() {
        return investid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debttransferapply.investid
     *
     * @param investid the value for debttransferapply.investid
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public void setInvestid(Integer investid) {
        this.investid = investid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debttransferapply.applytime
     *
     * @return the value of debttransferapply.applytime
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debttransferapply.applytime
     *
     * @param applytime the value for debttransferapply.applytime
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debttransferapply.checked
     *
     * @return the value of debttransferapply.checked
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public Boolean getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debttransferapply.checked
     *
     * @param checked the value for debttransferapply.checked
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public void setChecked(Boolean checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debttransferapply.servicecharge
     *
     * @return the value of debttransferapply.servicecharge
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public Double getServicecharge() {
        return servicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debttransferapply.servicecharge
     *
     * @param servicecharge the value for debttransferapply.servicecharge
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public void setServicecharge(Double servicecharge) {
        this.servicecharge = servicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debttransferapply.servicechargeid
     *
     * @return the value of debttransferapply.servicechargeid
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public Integer getServicechargeid() {
        return servicechargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debttransferapply.servicechargeid
     *
     * @param servicechargeid the value for debttransferapply.servicechargeid
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public void setServicechargeid(Integer servicechargeid) {
        this.servicechargeid = servicechargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debttransferapply.ispass
     *
     * @return the value of debttransferapply.ispass
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public Boolean getIspass() {
        return ispass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debttransferapply.ispass
     *
     * @param ispass the value for debttransferapply.ispass
     *
     * @mbggenerated Wed Aug 28 15:38:30 CST 2019
     */
    public void setIspass(Boolean ispass) {
        this.ispass = ispass;
    }
}