package com.woniu.domain;

import java.util.Date;


public class Debtinvest {
	
	private Debttransferdisplay display;
	
	public Debttransferdisplay getDisplay() {
		return display;
	}

	public void setDisplay(Debttransferdisplay display) {
		this.display = display;
	}

	private Userinfo userinfo;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debtinvest.debtinvestid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer debtinvestid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debtinvest.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer userinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debtinvest.investamount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double investamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debtinvest.paytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debtinvest.istransfer
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Boolean istransfer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debtinvest.servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double servicecharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debtinvest.servicechargeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer servicechargeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debtinvest.debttransferdisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer debttransferdisplay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debtinvest.debtinvestid
     *
     * @return the value of debtinvest.debtinvestid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getDebtinvestid() {
        return debtinvestid;
    }

    public Userinfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debtinvest.debtinvestid
     *
     * @param debtinvestid the value for debtinvest.debtinvestid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setDebtinvestid(Integer debtinvestid) {
        this.debtinvestid = debtinvestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debtinvest.userinfoid
     *
     * @return the value of debtinvest.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debtinvest.userinfoid
     *
     * @param userinfoid the value for debtinvest.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debtinvest.investamount
     *
     * @return the value of debtinvest.investamount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getInvestamount() {
        return investamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debtinvest.investamount
     *
     * @param investamount the value for debtinvest.investamount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setInvestamount(Double investamount) {
        this.investamount = investamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debtinvest.paytime
     *
     * @return the value of debtinvest.paytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debtinvest.paytime
     *
     * @param paytime the value for debtinvest.paytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debtinvest.istransfer
     *
     * @return the value of debtinvest.istransfer
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Boolean getIstransfer() {
        return istransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debtinvest.istransfer
     *
     * @param istransfer the value for debtinvest.istransfer
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setIstransfer(Boolean istransfer) {
        this.istransfer = istransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debtinvest.servicecharge
     *
     * @return the value of debtinvest.servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getServicecharge() {
        return servicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debtinvest.servicecharge
     *
     * @param servicecharge the value for debtinvest.servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setServicecharge(Double servicecharge) {
        this.servicecharge = servicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debtinvest.servicechargeid
     *
     * @return the value of debtinvest.servicechargeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getServicechargeid() {
        return servicechargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debtinvest.servicechargeid
     *
     * @param servicechargeid the value for debtinvest.servicechargeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setServicechargeid(Integer servicechargeid) {
        this.servicechargeid = servicechargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debtinvest.debttransferdisplay
     *
     * @return the value of debtinvest.debttransferdisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getDebttransferdisplay() {
        return debttransferdisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debtinvest.debttransferdisplay
     *
     * @param debttransferdisplay the value for debtinvest.debttransferdisplay
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setDebttransferdisplay(Integer debttransferdisplay) {
        this.debttransferdisplay = debttransferdisplay;
    }
}