package com.woniu.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonBackReference;

public class Invest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest.investid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer investid;
    private Loandisplay loandisplay;
    private Userinfo userinfo;

    public Userinfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer userinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest.investamount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double investamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest.paytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest.loandisplayid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer loandisplayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest.istransfer
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Boolean istransfer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest.servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double servicecharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest.servicechargeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer servicechargeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest.investid
     *
     * @return the value of invest.investid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getInvestid() {
        return investid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest.investid
     *
     * @param investid the value for invest.investid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    
    public void setInvestid(Integer investid) {
        this.investid = investid;
    }

    public Loandisplay getLoandisplay() {
		return loandisplay;
	}

	public void setLoandisplay(Loandisplay loandisplay) {
		this.loandisplay = loandisplay;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest.userinfoid
     *
     * @return the value of invest.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest.userinfoid
     *
     * @param userinfoid the value for invest.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest.investamount
     *
     * @return the value of invest.investamount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getInvestamount() {
        return investamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest.investamount
     *
     * @param investamount the value for invest.investamount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setInvestamount(Double investamount) {
        this.investamount = investamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest.paytime
     *
     * @return the value of invest.paytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest.paytime
     *
     * @param paytime the value for invest.paytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest.loandisplayid
     *
     * @return the value of invest.loandisplayid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getLoandisplayid() {
        return loandisplayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest.loandisplayid
     *
     * @param loandisplayid the value for invest.loandisplayid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setLoandisplayid(Integer loandisplayid) {
        this.loandisplayid = loandisplayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest.istransfer
     *
     * @return the value of invest.istransfer
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Boolean getIstransfer() {
        return istransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest.istransfer
     *
     * @param istransfer the value for invest.istransfer
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setIstransfer(Boolean istransfer) {
        this.istransfer = istransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest.servicecharge
     *
     * @return the value of invest.servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getServicecharge() {
        return servicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest.servicecharge
     *
     * @param servicecharge the value for invest.servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setServicecharge(Double servicecharge) {
        this.servicecharge = servicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest.servicechargeid
     *
     * @return the value of invest.servicechargeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getServicechargeid() {
        return servicechargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest.servicechargeid
     *
     * @param servicechargeid the value for invest.servicechargeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setServicechargeid(Integer servicechargeid) {
        this.servicechargeid = servicechargeid;
    }
}