package com.woniu.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoanapplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public LoanapplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLoanapplyidIsNull() {
            addCriterion("loanapplyid is null");
            return (Criteria) this;
        }

        public Criteria andLoanapplyidIsNotNull() {
            addCriterion("loanapplyid is not null");
            return (Criteria) this;
        }

        public Criteria andLoanapplyidEqualTo(Integer value) {
            addCriterion("loanapplyid =", value, "loanapplyid");
            return (Criteria) this;
        }

        public Criteria andLoanapplyidNotEqualTo(Integer value) {
            addCriterion("loanapplyid <>", value, "loanapplyid");
            return (Criteria) this;
        }

        public Criteria andLoanapplyidGreaterThan(Integer value) {
            addCriterion("loanapplyid >", value, "loanapplyid");
            return (Criteria) this;
        }

        public Criteria andLoanapplyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("loanapplyid >=", value, "loanapplyid");
            return (Criteria) this;
        }

        public Criteria andLoanapplyidLessThan(Integer value) {
            addCriterion("loanapplyid <", value, "loanapplyid");
            return (Criteria) this;
        }

        public Criteria andLoanapplyidLessThanOrEqualTo(Integer value) {
            addCriterion("loanapplyid <=", value, "loanapplyid");
            return (Criteria) this;
        }

        public Criteria andLoanapplyidIn(List<Integer> values) {
            addCriterion("loanapplyid in", values, "loanapplyid");
            return (Criteria) this;
        }

        public Criteria andLoanapplyidNotIn(List<Integer> values) {
            addCriterion("loanapplyid not in", values, "loanapplyid");
            return (Criteria) this;
        }

        public Criteria andLoanapplyidBetween(Integer value1, Integer value2) {
            addCriterion("loanapplyid between", value1, value2, "loanapplyid");
            return (Criteria) this;
        }

        public Criteria andLoanapplyidNotBetween(Integer value1, Integer value2) {
            addCriterion("loanapplyid not between", value1, value2, "loanapplyid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidIsNull() {
            addCriterion("userinfoid is null");
            return (Criteria) this;
        }

        public Criteria andUserinfoidIsNotNull() {
            addCriterion("userinfoid is not null");
            return (Criteria) this;
        }

        public Criteria andUserinfoidEqualTo(Integer value) {
            addCriterion("userinfoid =", value, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidNotEqualTo(Integer value) {
            addCriterion("userinfoid <>", value, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidGreaterThan(Integer value) {
            addCriterion("userinfoid >", value, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidGreaterThanOrEqualTo(Integer value) {
            addCriterion("userinfoid >=", value, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidLessThan(Integer value) {
            addCriterion("userinfoid <", value, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidLessThanOrEqualTo(Integer value) {
            addCriterion("userinfoid <=", value, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidIn(List<Integer> values) {
            addCriterion("userinfoid in", values, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidNotIn(List<Integer> values) {
            addCriterion("userinfoid not in", values, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidBetween(Integer value1, Integer value2) {
            addCriterion("userinfoid between", value1, value2, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidNotBetween(Integer value1, Integer value2) {
            addCriterion("userinfoid not between", value1, value2, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andLoanamountIsNull() {
            addCriterion("loanamount is null");
            return (Criteria) this;
        }

        public Criteria andLoanamountIsNotNull() {
            addCriterion("loanamount is not null");
            return (Criteria) this;
        }

        public Criteria andLoanamountEqualTo(Double value) {
            addCriterion("loanamount =", value, "loanamount");
            return (Criteria) this;
        }

        public Criteria andLoanamountNotEqualTo(Double value) {
            addCriterion("loanamount <>", value, "loanamount");
            return (Criteria) this;
        }

        public Criteria andLoanamountGreaterThan(Double value) {
            addCriterion("loanamount >", value, "loanamount");
            return (Criteria) this;
        }

        public Criteria andLoanamountGreaterThanOrEqualTo(Double value) {
            addCriterion("loanamount >=", value, "loanamount");
            return (Criteria) this;
        }

        public Criteria andLoanamountLessThan(Double value) {
            addCriterion("loanamount <", value, "loanamount");
            return (Criteria) this;
        }

        public Criteria andLoanamountLessThanOrEqualTo(Double value) {
            addCriterion("loanamount <=", value, "loanamount");
            return (Criteria) this;
        }

        public Criteria andLoanamountIn(List<Double> values) {
            addCriterion("loanamount in", values, "loanamount");
            return (Criteria) this;
        }

        public Criteria andLoanamountNotIn(List<Double> values) {
            addCriterion("loanamount not in", values, "loanamount");
            return (Criteria) this;
        }

        public Criteria andLoanamountBetween(Double value1, Double value2) {
            addCriterion("loanamount between", value1, value2, "loanamount");
            return (Criteria) this;
        }

        public Criteria andLoanamountNotBetween(Double value1, Double value2) {
            addCriterion("loanamount not between", value1, value2, "loanamount");
            return (Criteria) this;
        }

        public Criteria andApplytimeIsNull() {
            addCriterion("applytime is null");
            return (Criteria) this;
        }

        public Criteria andApplytimeIsNotNull() {
            addCriterion("applytime is not null");
            return (Criteria) this;
        }

        public Criteria andApplytimeEqualTo(Date value) {
            addCriterion("applytime =", value, "applytime");
            return (Criteria) this;
        }

        public Criteria andApplytimeNotEqualTo(Date value) {
            addCriterion("applytime <>", value, "applytime");
            return (Criteria) this;
        }

        public Criteria andApplytimeGreaterThan(Date value) {
            addCriterion("applytime >", value, "applytime");
            return (Criteria) this;
        }

        public Criteria andApplytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("applytime >=", value, "applytime");
            return (Criteria) this;
        }

        public Criteria andApplytimeLessThan(Date value) {
            addCriterion("applytime <", value, "applytime");
            return (Criteria) this;
        }

        public Criteria andApplytimeLessThanOrEqualTo(Date value) {
            addCriterion("applytime <=", value, "applytime");
            return (Criteria) this;
        }

        public Criteria andApplytimeIn(List<Date> values) {
            addCriterion("applytime in", values, "applytime");
            return (Criteria) this;
        }

        public Criteria andApplytimeNotIn(List<Date> values) {
            addCriterion("applytime not in", values, "applytime");
            return (Criteria) this;
        }

        public Criteria andApplytimeBetween(Date value1, Date value2) {
            addCriterion("applytime between", value1, value2, "applytime");
            return (Criteria) this;
        }

        public Criteria andApplytimeNotBetween(Date value1, Date value2) {
            addCriterion("applytime not between", value1, value2, "applytime");
            return (Criteria) this;
        }

        public Criteria andCheckedIsNull() {
            addCriterion("checked is null");
            return (Criteria) this;
        }

        public Criteria andCheckedIsNotNull() {
            addCriterion("checked is not null");
            return (Criteria) this;
        }

        public Criteria andCheckedEqualTo(Boolean value) {
            addCriterion("checked =", value, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedNotEqualTo(Boolean value) {
            addCriterion("checked <>", value, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedGreaterThan(Boolean value) {
            addCriterion("checked >", value, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("checked >=", value, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedLessThan(Boolean value) {
            addCriterion("checked <", value, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedLessThanOrEqualTo(Boolean value) {
            addCriterion("checked <=", value, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedIn(List<Boolean> values) {
            addCriterion("checked in", values, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedNotIn(List<Boolean> values) {
            addCriterion("checked not in", values, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedBetween(Boolean value1, Boolean value2) {
            addCriterion("checked between", value1, value2, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("checked not between", value1, value2, "checked");
            return (Criteria) this;
        }

        public Criteria andLoantimeidIsNull() {
            addCriterion("loantimeid is null");
            return (Criteria) this;
        }

        public Criteria andLoantimeidIsNotNull() {
            addCriterion("loantimeid is not null");
            return (Criteria) this;
        }

        public Criteria andLoantimeidEqualTo(Integer value) {
            addCriterion("loantimeid =", value, "loantimeid");
            return (Criteria) this;
        }

        public Criteria andLoantimeidNotEqualTo(Integer value) {
            addCriterion("loantimeid <>", value, "loantimeid");
            return (Criteria) this;
        }

        public Criteria andLoantimeidGreaterThan(Integer value) {
            addCriterion("loantimeid >", value, "loantimeid");
            return (Criteria) this;
        }

        public Criteria andLoantimeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("loantimeid >=", value, "loantimeid");
            return (Criteria) this;
        }

        public Criteria andLoantimeidLessThan(Integer value) {
            addCriterion("loantimeid <", value, "loantimeid");
            return (Criteria) this;
        }

        public Criteria andLoantimeidLessThanOrEqualTo(Integer value) {
            addCriterion("loantimeid <=", value, "loantimeid");
            return (Criteria) this;
        }

        public Criteria andLoantimeidIn(List<Integer> values) {
            addCriterion("loantimeid in", values, "loantimeid");
            return (Criteria) this;
        }

        public Criteria andLoantimeidNotIn(List<Integer> values) {
            addCriterion("loantimeid not in", values, "loantimeid");
            return (Criteria) this;
        }

        public Criteria andLoantimeidBetween(Integer value1, Integer value2) {
            addCriterion("loantimeid between", value1, value2, "loantimeid");
            return (Criteria) this;
        }

        public Criteria andLoantimeidNotBetween(Integer value1, Integer value2) {
            addCriterion("loantimeid not between", value1, value2, "loantimeid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidIsNull() {
            addCriterion("loanrateid is null");
            return (Criteria) this;
        }

        public Criteria andLoanrateidIsNotNull() {
            addCriterion("loanrateid is not null");
            return (Criteria) this;
        }

        public Criteria andLoanrateidEqualTo(Integer value) {
            addCriterion("loanrateid =", value, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidNotEqualTo(Integer value) {
            addCriterion("loanrateid <>", value, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidGreaterThan(Integer value) {
            addCriterion("loanrateid >", value, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidGreaterThanOrEqualTo(Integer value) {
            addCriterion("loanrateid >=", value, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidLessThan(Integer value) {
            addCriterion("loanrateid <", value, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidLessThanOrEqualTo(Integer value) {
            addCriterion("loanrateid <=", value, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidIn(List<Integer> values) {
            addCriterion("loanrateid in", values, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidNotIn(List<Integer> values) {
            addCriterion("loanrateid not in", values, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidBetween(Integer value1, Integer value2) {
            addCriterion("loanrateid between", value1, value2, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidNotBetween(Integer value1, Integer value2) {
            addCriterion("loanrateid not between", value1, value2, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andServicechargeIsNull() {
            addCriterion("servicecharge is null");
            return (Criteria) this;
        }

        public Criteria andServicechargeIsNotNull() {
            addCriterion("servicecharge is not null");
            return (Criteria) this;
        }

        public Criteria andServicechargeEqualTo(Double value) {
            addCriterion("servicecharge =", value, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeNotEqualTo(Double value) {
            addCriterion("servicecharge <>", value, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeGreaterThan(Double value) {
            addCriterion("servicecharge >", value, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeGreaterThanOrEqualTo(Double value) {
            addCriterion("servicecharge >=", value, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeLessThan(Double value) {
            addCriterion("servicecharge <", value, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeLessThanOrEqualTo(Double value) {
            addCriterion("servicecharge <=", value, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeIn(List<Double> values) {
            addCriterion("servicecharge in", values, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeNotIn(List<Double> values) {
            addCriterion("servicecharge not in", values, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeBetween(Double value1, Double value2) {
            addCriterion("servicecharge between", value1, value2, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeNotBetween(Double value1, Double value2) {
            addCriterion("servicecharge not between", value1, value2, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeidIsNull() {
            addCriterion("servicechargeid is null");
            return (Criteria) this;
        }

        public Criteria andServicechargeidIsNotNull() {
            addCriterion("servicechargeid is not null");
            return (Criteria) this;
        }

        public Criteria andServicechargeidEqualTo(Integer value) {
            addCriterion("servicechargeid =", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidNotEqualTo(Integer value) {
            addCriterion("servicechargeid <>", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidGreaterThan(Integer value) {
            addCriterion("servicechargeid >", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("servicechargeid >=", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidLessThan(Integer value) {
            addCriterion("servicechargeid <", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidLessThanOrEqualTo(Integer value) {
            addCriterion("servicechargeid <=", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidIn(List<Integer> values) {
            addCriterion("servicechargeid in", values, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidNotIn(List<Integer> values) {
            addCriterion("servicechargeid not in", values, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidBetween(Integer value1, Integer value2) {
            addCriterion("servicechargeid between", value1, value2, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidNotBetween(Integer value1, Integer value2) {
            addCriterion("servicechargeid not between", value1, value2, "servicechargeid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loanapply
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 15:11:02 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loanapply
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}