package com.woniu.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoantimeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	public LoantimeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andLoantimeidIsNull() {
			addCriterion("loantimeid is null");
			return (Criteria) this;
		}

		public Criteria andLoantimeidIsNotNull() {
			addCriterion("loantimeid is not null");
			return (Criteria) this;
		}

		public Criteria andLoantimeidEqualTo(Integer value) {
			addCriterion("loantimeid =", value, "loantimeid");
			return (Criteria) this;
		}

		public Criteria andLoantimeidNotEqualTo(Integer value) {
			addCriterion("loantimeid <>", value, "loantimeid");
			return (Criteria) this;
		}

		public Criteria andLoantimeidGreaterThan(Integer value) {
			addCriterion("loantimeid >", value, "loantimeid");
			return (Criteria) this;
		}

		public Criteria andLoantimeidGreaterThanOrEqualTo(Integer value) {
			addCriterion("loantimeid >=", value, "loantimeid");
			return (Criteria) this;
		}

		public Criteria andLoantimeidLessThan(Integer value) {
			addCriterion("loantimeid <", value, "loantimeid");
			return (Criteria) this;
		}

		public Criteria andLoantimeidLessThanOrEqualTo(Integer value) {
			addCriterion("loantimeid <=", value, "loantimeid");
			return (Criteria) this;
		}

		public Criteria andLoantimeidIn(List<Integer> values) {
			addCriterion("loantimeid in", values, "loantimeid");
			return (Criteria) this;
		}

		public Criteria andLoantimeidNotIn(List<Integer> values) {
			addCriterion("loantimeid not in", values, "loantimeid");
			return (Criteria) this;
		}

		public Criteria andLoantimeidBetween(Integer value1, Integer value2) {
			addCriterion("loantimeid between", value1, value2, "loantimeid");
			return (Criteria) this;
		}

		public Criteria andLoantimeidNotBetween(Integer value1, Integer value2) {
			addCriterion("loantimeid not between", value1, value2, "loantimeid");
			return (Criteria) this;
		}

		public Criteria andLoantimeIsNull() {
			addCriterion("loantime is null");
			return (Criteria) this;
		}

		public Criteria andLoantimeIsNotNull() {
			addCriterion("loantime is not null");
			return (Criteria) this;
		}

		public Criteria andLoantimeEqualTo(Integer value) {
			addCriterion("loantime =", value, "loantime");
			return (Criteria) this;
		}

		public Criteria andLoantimeNotEqualTo(Integer value) {
			addCriterion("loantime <>", value, "loantime");
			return (Criteria) this;
		}

		public Criteria andLoantimeGreaterThan(Integer value) {
			addCriterion("loantime >", value, "loantime");
			return (Criteria) this;
		}

		public Criteria andLoantimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("loantime >=", value, "loantime");
			return (Criteria) this;
		}

		public Criteria andLoantimeLessThan(Integer value) {
			addCriterion("loantime <", value, "loantime");
			return (Criteria) this;
		}

		public Criteria andLoantimeLessThanOrEqualTo(Integer value) {
			addCriterion("loantime <=", value, "loantime");
			return (Criteria) this;
		}

		public Criteria andLoantimeIn(List<Integer> values) {
			addCriterion("loantime in", values, "loantime");
			return (Criteria) this;
		}

		public Criteria andLoantimeNotIn(List<Integer> values) {
			addCriterion("loantime not in", values, "loantime");
			return (Criteria) this;
		}

		public Criteria andLoantimeBetween(Integer value1, Integer value2) {
			addCriterion("loantime between", value1, value2, "loantime");
			return (Criteria) this;
		}

		public Criteria andLoantimeNotBetween(Integer value1, Integer value2) {
			addCriterion("loantime not between", value1, value2, "loantime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table loantime
	 * @mbggenerated  Mon Aug 26 15:04:38 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loantime
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 15:11:02 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}