package com.woniu.domain;

import java.util.ArrayList;
import java.util.List;

public class LoanrateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public LoanrateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLoanrateidIsNull() {
            addCriterion("loanrateid is null");
            return (Criteria) this;
        }

        public Criteria andLoanrateidIsNotNull() {
            addCriterion("loanrateid is not null");
            return (Criteria) this;
        }

        public Criteria andLoanrateidEqualTo(Integer value) {
            addCriterion("loanrateid =", value, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidNotEqualTo(Integer value) {
            addCriterion("loanrateid <>", value, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidGreaterThan(Integer value) {
            addCriterion("loanrateid >", value, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidGreaterThanOrEqualTo(Integer value) {
            addCriterion("loanrateid >=", value, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidLessThan(Integer value) {
            addCriterion("loanrateid <", value, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidLessThanOrEqualTo(Integer value) {
            addCriterion("loanrateid <=", value, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidIn(List<Integer> values) {
            addCriterion("loanrateid in", values, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidNotIn(List<Integer> values) {
            addCriterion("loanrateid not in", values, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidBetween(Integer value1, Integer value2) {
            addCriterion("loanrateid between", value1, value2, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateidNotBetween(Integer value1, Integer value2) {
            addCriterion("loanrateid not between", value1, value2, "loanrateid");
            return (Criteria) this;
        }

        public Criteria andLoanrateIsNull() {
            addCriterion("loanrate is null");
            return (Criteria) this;
        }

        public Criteria andLoanrateIsNotNull() {
            addCriterion("loanrate is not null");
            return (Criteria) this;
        }

        public Criteria andLoanrateEqualTo(Double value) {
            addCriterion("loanrate =", value, "loanrate");
            return (Criteria) this;
        }

        public Criteria andLoanrateNotEqualTo(Double value) {
            addCriterion("loanrate <>", value, "loanrate");
            return (Criteria) this;
        }

        public Criteria andLoanrateGreaterThan(Double value) {
            addCriterion("loanrate >", value, "loanrate");
            return (Criteria) this;
        }

        public Criteria andLoanrateGreaterThanOrEqualTo(Double value) {
            addCriterion("loanrate >=", value, "loanrate");
            return (Criteria) this;
        }

        public Criteria andLoanrateLessThan(Double value) {
            addCriterion("loanrate <", value, "loanrate");
            return (Criteria) this;
        }

        public Criteria andLoanrateLessThanOrEqualTo(Double value) {
            addCriterion("loanrate <=", value, "loanrate");
            return (Criteria) this;
        }

        public Criteria andLoanrateIn(List<Double> values) {
            addCriterion("loanrate in", values, "loanrate");
            return (Criteria) this;
        }

        public Criteria andLoanrateNotIn(List<Double> values) {
            addCriterion("loanrate not in", values, "loanrate");
            return (Criteria) this;
        }

        public Criteria andLoanrateBetween(Double value1, Double value2) {
            addCriterion("loanrate between", value1, value2, "loanrate");
            return (Criteria) this;
        }

        public Criteria andLoanrateNotBetween(Double value1, Double value2) {
            addCriterion("loanrate not between", value1, value2, "loanrate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loanrate
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 15:11:02 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}