package com.woniu.domain;

import java.util.Date;

public class Loandisplay {
	private Loanapply loanapply;
    public Loanapply getLoanapply() {
		return loanapply;
	}

	public void setLoanapply(Loanapply loanapply) {
		this.loanapply = loanapply;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loandisplay.loandisplayid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer loandisplayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loandisplay.displaytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Date displaytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loandisplay.deadtime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Date deadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loandisplay.isfinished
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Boolean isfinished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loandisplay.isdead
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Boolean isdead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loandisplay.loanapplyid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer loanapplyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loandisplay.loandisplayid
     *
     * @return the value of loandisplay.loandisplayid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getLoandisplayid() {
        return loandisplayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loandisplay.loandisplayid
     *
     * @param loandisplayid the value for loandisplay.loandisplayid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setLoandisplayid(Integer loandisplayid) {
        this.loandisplayid = loandisplayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loandisplay.displaytime
     *
     * @return the value of loandisplay.displaytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Date getDisplaytime() {
        return displaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loandisplay.displaytime
     *
     * @param displaytime the value for loandisplay.displaytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setDisplaytime(Date displaytime) {
        this.displaytime = displaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loandisplay.deadtime
     *
     * @return the value of loandisplay.deadtime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Date getDeadtime() {
        return deadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loandisplay.deadtime
     *
     * @param deadtime the value for loandisplay.deadtime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setDeadtime(Date deadtime) {
        this.deadtime = deadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loandisplay.isfinished
     *
     * @return the value of loandisplay.isfinished
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Boolean getIsfinished() {
        return isfinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loandisplay.isfinished
     *
     * @param isfinished the value for loandisplay.isfinished
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setIsfinished(Boolean isfinished) {
        this.isfinished = isfinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loandisplay.isdead
     *
     * @return the value of loandisplay.isdead
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Boolean getIsdead() {
        return isdead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loandisplay.isdead
     *
     * @param isdead the value for loandisplay.isdead
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setIsdead(Boolean isdead) {
        this.isdead = isdead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loandisplay.loanapplyid
     *
     * @return the value of loandisplay.loanapplyid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getLoanapplyid() {
        return loanapplyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loandisplay.loanapplyid
     *
     * @param loanapplyid the value for loandisplay.loanapplyid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setLoanapplyid(Integer loanapplyid) {
        this.loanapplyid = loanapplyid;
    }
}