package com.woniu.domain;

public class Loanrate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loanrate.loanrateid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer loanrateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loanrate.loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double loanrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loanrate.loanrateid
     *
     * @return the value of loanrate.loanrateid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getLoanrateid() {
        return loanrateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loanrate.loanrateid
     *
     * @param loanrateid the value for loanrate.loanrateid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setLoanrateid(Integer loanrateid) {
        this.loanrateid = loanrateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loanrate.loanrate
     *
     * @return the value of loanrate.loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getLoanrate() {
        return loanrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loanrate.loanrate
     *
     * @param loanrate the value for loanrate.loanrate
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setLoanrate(Double loanrate) {
        this.loanrate = loanrate;
    }
}