package com.woniu.domain;

import java.util.Date;

public class Loanapply {
    @Override
	public String toString() {
		return "Loanapply [loanapplyid=" + loanapplyid + ", userinfoid=" + userinfoid + ", loanamount=" + loanamount
				+ ", applytime=" + applytime + ", checked=" + checked + ", loantimeid=" + loantimeid + ", loanrateid="
				+ loanrateid + ", servicecharge=" + servicecharge + ", servicechargeid=" + servicechargeid + ", reason="
				+ reason + "]";
		}
	private Loanrate loanrate;
	
    public Loanrate getLoanrate() {
		return loanrate;
	}

	public void setLoanrate(Loanrate loanrate) {
		this.loanrate = loanrate;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loanapply.loanapplyid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer loanapplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loanapply.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer userinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loanapply.loanamount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double loanamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loanapply.applytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Date applytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loanapply.checked
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Boolean checked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loanapply.loantimeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer loantimeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loanapply.loanrateid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer loanrateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loanapply.servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double servicecharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loanapply.servicechargeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer servicechargeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loanapply.reason
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loanapply.loanapplyid
     *
     * @return the value of loanapply.loanapplyid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getLoanapplyid() {
        return loanapplyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loanapply.loanapplyid
     *
     * @param loanapplyid the value for loanapply.loanapplyid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setLoanapplyid(Integer loanapplyid) {
        this.loanapplyid = loanapplyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loanapply.userinfoid
     *
     * @return the value of loanapply.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loanapply.userinfoid
     *
     * @param userinfoid the value for loanapply.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loanapply.loanamount
     *
     * @return the value of loanapply.loanamount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getLoanamount() {
        return loanamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loanapply.loanamount
     *
     * @param loanamount the value for loanapply.loanamount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setLoanamount(Double loanamount) {
        this.loanamount = loanamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loanapply.applytime
     *
     * @return the value of loanapply.applytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loanapply.applytime
     *
     * @param applytime the value for loanapply.applytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loanapply.checked
     *
     * @return the value of loanapply.checked
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Boolean getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loanapply.checked
     *
     * @param checked the value for loanapply.checked
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setChecked(Boolean checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loanapply.loantimeid
     *
     * @return the value of loanapply.loantimeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getLoantimeid() {
        return loantimeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loanapply.loantimeid
     *
     * @param loantimeid the value for loanapply.loantimeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setLoantimeid(Integer loantimeid) {
        this.loantimeid = loantimeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loanapply.loanrateid
     *
     * @return the value of loanapply.loanrateid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getLoanrateid() {
        return loanrateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loanapply.loanrateid
     *
     * @param loanrateid the value for loanapply.loanrateid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setLoanrateid(Integer loanrateid) {
        this.loanrateid = loanrateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loanapply.servicecharge
     *
     * @return the value of loanapply.servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getServicecharge() {
        return servicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loanapply.servicecharge
     *
     * @param servicecharge the value for loanapply.servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setServicecharge(Double servicecharge) {
        this.servicecharge = servicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loanapply.servicechargeid
     *
     * @return the value of loanapply.servicechargeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getServicechargeid() {
        return servicechargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loanapply.servicechargeid
     *
     * @param servicechargeid the value for loanapply.servicechargeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setServicechargeid(Integer servicechargeid) {
        this.servicechargeid = servicechargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loanapply.reason
     *
     * @return the value of loanapply.reason
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loanapply.reason
     *
     * @param reason the value for loanapply.reason
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason;
    }
}