package com.woniu.domain;

import java.util.Date;

public class RechargeWithdraw {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_withdraw.recharge_withdraw_id
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer rechargeWithdrawId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_withdraw.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer userinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_withdraw.recharge_withdraw_amount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double rechargeWithdrawAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_withdraw.recharge_withdraw_time
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Date rechargeWithdrawTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_withdraw.servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double servicecharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_withdraw.servicechargeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer servicechargeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_withdraw.transactionserialnum
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Long transactionserialnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_withdraw.transactiontypeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer transactiontypeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_withdraw.recharge_withdraw_id
     *
     * @return the value of recharge_withdraw.recharge_withdraw_id
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getRechargeWithdrawId() {
        return rechargeWithdrawId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_withdraw.recharge_withdraw_id
     *
     * @param rechargeWithdrawId the value for recharge_withdraw.recharge_withdraw_id
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setRechargeWithdrawId(Integer rechargeWithdrawId) {
        this.rechargeWithdrawId = rechargeWithdrawId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_withdraw.userinfoid
     *
     * @return the value of recharge_withdraw.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_withdraw.userinfoid
     *
     * @param userinfoid the value for recharge_withdraw.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_withdraw.recharge_withdraw_amount
     *
     * @return the value of recharge_withdraw.recharge_withdraw_amount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getRechargeWithdrawAmount() {
        return rechargeWithdrawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_withdraw.recharge_withdraw_amount
     *
     * @param rechargeWithdrawAmount the value for recharge_withdraw.recharge_withdraw_amount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setRechargeWithdrawAmount(Double rechargeWithdrawAmount) {
        this.rechargeWithdrawAmount = rechargeWithdrawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_withdraw.recharge_withdraw_time
     *
     * @return the value of recharge_withdraw.recharge_withdraw_time
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Date getRechargeWithdrawTime() {
        return rechargeWithdrawTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_withdraw.recharge_withdraw_time
     *
     * @param rechargeWithdrawTime the value for recharge_withdraw.recharge_withdraw_time
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setRechargeWithdrawTime(Date rechargeWithdrawTime) {
        this.rechargeWithdrawTime = rechargeWithdrawTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_withdraw.servicecharge
     *
     * @return the value of recharge_withdraw.servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getServicecharge() {
        return servicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_withdraw.servicecharge
     *
     * @param servicecharge the value for recharge_withdraw.servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setServicecharge(Double servicecharge) {
        this.servicecharge = servicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_withdraw.servicechargeid
     *
     * @return the value of recharge_withdraw.servicechargeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getServicechargeid() {
        return servicechargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_withdraw.servicechargeid
     *
     * @param servicechargeid the value for recharge_withdraw.servicechargeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setServicechargeid(Integer servicechargeid) {
        this.servicechargeid = servicechargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_withdraw.transactionserialnum
     *
     * @return the value of recharge_withdraw.transactionserialnum
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Long getTransactionserialnum() {
        return transactionserialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_withdraw.transactionserialnum
     *
     * @param transactionserialnum the value for recharge_withdraw.transactionserialnum
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setTransactionserialnum(Long transactionserialnum) {
        this.transactionserialnum = transactionserialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_withdraw.transactiontypeid
     *
     * @return the value of recharge_withdraw.transactiontypeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getTransactiontypeid() {
        return transactiontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_withdraw.transactiontypeid
     *
     * @param transactiontypeid the value for recharge_withdraw.transactiontypeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setTransactiontypeid(Integer transactiontypeid) {
        this.transactiontypeid = transactiontypeid;
    }
}