package com.woniu.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RechargeWithdrawExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public RechargeWithdrawExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRechargeWithdrawIdIsNull() {
            addCriterion("recharge_withdraw_id is null");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawIdIsNotNull() {
            addCriterion("recharge_withdraw_id is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawIdEqualTo(Integer value) {
            addCriterion("recharge_withdraw_id =", value, "rechargeWithdrawId");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawIdNotEqualTo(Integer value) {
            addCriterion("recharge_withdraw_id <>", value, "rechargeWithdrawId");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawIdGreaterThan(Integer value) {
            addCriterion("recharge_withdraw_id >", value, "rechargeWithdrawId");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("recharge_withdraw_id >=", value, "rechargeWithdrawId");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawIdLessThan(Integer value) {
            addCriterion("recharge_withdraw_id <", value, "rechargeWithdrawId");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawIdLessThanOrEqualTo(Integer value) {
            addCriterion("recharge_withdraw_id <=", value, "rechargeWithdrawId");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawIdIn(List<Integer> values) {
            addCriterion("recharge_withdraw_id in", values, "rechargeWithdrawId");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawIdNotIn(List<Integer> values) {
            addCriterion("recharge_withdraw_id not in", values, "rechargeWithdrawId");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawIdBetween(Integer value1, Integer value2) {
            addCriterion("recharge_withdraw_id between", value1, value2, "rechargeWithdrawId");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawIdNotBetween(Integer value1, Integer value2) {
            addCriterion("recharge_withdraw_id not between", value1, value2, "rechargeWithdrawId");
            return (Criteria) this;
        }

        public Criteria andUserinfoidIsNull() {
            addCriterion("userinfoid is null");
            return (Criteria) this;
        }

        public Criteria andUserinfoidIsNotNull() {
            addCriterion("userinfoid is not null");
            return (Criteria) this;
        }

        public Criteria andUserinfoidEqualTo(Integer value) {
            addCriterion("userinfoid =", value, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidNotEqualTo(Integer value) {
            addCriterion("userinfoid <>", value, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidGreaterThan(Integer value) {
            addCriterion("userinfoid >", value, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidGreaterThanOrEqualTo(Integer value) {
            addCriterion("userinfoid >=", value, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidLessThan(Integer value) {
            addCriterion("userinfoid <", value, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidLessThanOrEqualTo(Integer value) {
            addCriterion("userinfoid <=", value, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidIn(List<Integer> values) {
            addCriterion("userinfoid in", values, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidNotIn(List<Integer> values) {
            addCriterion("userinfoid not in", values, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidBetween(Integer value1, Integer value2) {
            addCriterion("userinfoid between", value1, value2, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andUserinfoidNotBetween(Integer value1, Integer value2) {
            addCriterion("userinfoid not between", value1, value2, "userinfoid");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawAmountIsNull() {
            addCriterion("recharge_withdraw_amount is null");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawAmountIsNotNull() {
            addCriterion("recharge_withdraw_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawAmountEqualTo(Double value) {
            addCriterion("recharge_withdraw_amount =", value, "rechargeWithdrawAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawAmountNotEqualTo(Double value) {
            addCriterion("recharge_withdraw_amount <>", value, "rechargeWithdrawAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawAmountGreaterThan(Double value) {
            addCriterion("recharge_withdraw_amount >", value, "rechargeWithdrawAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("recharge_withdraw_amount >=", value, "rechargeWithdrawAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawAmountLessThan(Double value) {
            addCriterion("recharge_withdraw_amount <", value, "rechargeWithdrawAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawAmountLessThanOrEqualTo(Double value) {
            addCriterion("recharge_withdraw_amount <=", value, "rechargeWithdrawAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawAmountIn(List<Double> values) {
            addCriterion("recharge_withdraw_amount in", values, "rechargeWithdrawAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawAmountNotIn(List<Double> values) {
            addCriterion("recharge_withdraw_amount not in", values, "rechargeWithdrawAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawAmountBetween(Double value1, Double value2) {
            addCriterion("recharge_withdraw_amount between", value1, value2, "rechargeWithdrawAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawAmountNotBetween(Double value1, Double value2) {
            addCriterion("recharge_withdraw_amount not between", value1, value2, "rechargeWithdrawAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawTimeIsNull() {
            addCriterion("recharge_withdraw_time is null");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawTimeIsNotNull() {
            addCriterion("recharge_withdraw_time is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawTimeEqualTo(Date value) {
            addCriterion("recharge_withdraw_time =", value, "rechargeWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawTimeNotEqualTo(Date value) {
            addCriterion("recharge_withdraw_time <>", value, "rechargeWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawTimeGreaterThan(Date value) {
            addCriterion("recharge_withdraw_time >", value, "rechargeWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("recharge_withdraw_time >=", value, "rechargeWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawTimeLessThan(Date value) {
            addCriterion("recharge_withdraw_time <", value, "rechargeWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawTimeLessThanOrEqualTo(Date value) {
            addCriterion("recharge_withdraw_time <=", value, "rechargeWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawTimeIn(List<Date> values) {
            addCriterion("recharge_withdraw_time in", values, "rechargeWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawTimeNotIn(List<Date> values) {
            addCriterion("recharge_withdraw_time not in", values, "rechargeWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawTimeBetween(Date value1, Date value2) {
            addCriterion("recharge_withdraw_time between", value1, value2, "rechargeWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andRechargeWithdrawTimeNotBetween(Date value1, Date value2) {
            addCriterion("recharge_withdraw_time not between", value1, value2, "rechargeWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andServicechargeIsNull() {
            addCriterion("servicecharge is null");
            return (Criteria) this;
        }

        public Criteria andServicechargeIsNotNull() {
            addCriterion("servicecharge is not null");
            return (Criteria) this;
        }

        public Criteria andServicechargeEqualTo(Double value) {
            addCriterion("servicecharge =", value, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeNotEqualTo(Double value) {
            addCriterion("servicecharge <>", value, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeGreaterThan(Double value) {
            addCriterion("servicecharge >", value, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeGreaterThanOrEqualTo(Double value) {
            addCriterion("servicecharge >=", value, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeLessThan(Double value) {
            addCriterion("servicecharge <", value, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeLessThanOrEqualTo(Double value) {
            addCriterion("servicecharge <=", value, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeIn(List<Double> values) {
            addCriterion("servicecharge in", values, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeNotIn(List<Double> values) {
            addCriterion("servicecharge not in", values, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeBetween(Double value1, Double value2) {
            addCriterion("servicecharge between", value1, value2, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeNotBetween(Double value1, Double value2) {
            addCriterion("servicecharge not between", value1, value2, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeidIsNull() {
            addCriterion("servicechargeid is null");
            return (Criteria) this;
        }

        public Criteria andServicechargeidIsNotNull() {
            addCriterion("servicechargeid is not null");
            return (Criteria) this;
        }

        public Criteria andServicechargeidEqualTo(Integer value) {
            addCriterion("servicechargeid =", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidNotEqualTo(Integer value) {
            addCriterion("servicechargeid <>", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidGreaterThan(Integer value) {
            addCriterion("servicechargeid >", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("servicechargeid >=", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidLessThan(Integer value) {
            addCriterion("servicechargeid <", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidLessThanOrEqualTo(Integer value) {
            addCriterion("servicechargeid <=", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidIn(List<Integer> values) {
            addCriterion("servicechargeid in", values, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidNotIn(List<Integer> values) {
            addCriterion("servicechargeid not in", values, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidBetween(Integer value1, Integer value2) {
            addCriterion("servicechargeid between", value1, value2, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidNotBetween(Integer value1, Integer value2) {
            addCriterion("servicechargeid not between", value1, value2, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andTransactionserialnumIsNull() {
            addCriterion("transactionserialnum is null");
            return (Criteria) this;
        }

        public Criteria andTransactionserialnumIsNotNull() {
            addCriterion("transactionserialnum is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionserialnumEqualTo(Long value) {
            addCriterion("transactionserialnum =", value, "transactionserialnum");
            return (Criteria) this;
        }

        public Criteria andTransactionserialnumNotEqualTo(Long value) {
            addCriterion("transactionserialnum <>", value, "transactionserialnum");
            return (Criteria) this;
        }

        public Criteria andTransactionserialnumGreaterThan(Long value) {
            addCriterion("transactionserialnum >", value, "transactionserialnum");
            return (Criteria) this;
        }

        public Criteria andTransactionserialnumGreaterThanOrEqualTo(Long value) {
            addCriterion("transactionserialnum >=", value, "transactionserialnum");
            return (Criteria) this;
        }

        public Criteria andTransactionserialnumLessThan(Long value) {
            addCriterion("transactionserialnum <", value, "transactionserialnum");
            return (Criteria) this;
        }

        public Criteria andTransactionserialnumLessThanOrEqualTo(Long value) {
            addCriterion("transactionserialnum <=", value, "transactionserialnum");
            return (Criteria) this;
        }

        public Criteria andTransactionserialnumIn(List<Long> values) {
            addCriterion("transactionserialnum in", values, "transactionserialnum");
            return (Criteria) this;
        }

        public Criteria andTransactionserialnumNotIn(List<Long> values) {
            addCriterion("transactionserialnum not in", values, "transactionserialnum");
            return (Criteria) this;
        }

        public Criteria andTransactionserialnumBetween(Long value1, Long value2) {
            addCriterion("transactionserialnum between", value1, value2, "transactionserialnum");
            return (Criteria) this;
        }

        public Criteria andTransactionserialnumNotBetween(Long value1, Long value2) {
            addCriterion("transactionserialnum not between", value1, value2, "transactionserialnum");
            return (Criteria) this;
        }

        public Criteria andTransactiontypeidIsNull() {
            addCriterion("transactiontypeid is null");
            return (Criteria) this;
        }

        public Criteria andTransactiontypeidIsNotNull() {
            addCriterion("transactiontypeid is not null");
            return (Criteria) this;
        }

        public Criteria andTransactiontypeidEqualTo(Integer value) {
            addCriterion("transactiontypeid =", value, "transactiontypeid");
            return (Criteria) this;
        }

        public Criteria andTransactiontypeidNotEqualTo(Integer value) {
            addCriterion("transactiontypeid <>", value, "transactiontypeid");
            return (Criteria) this;
        }

        public Criteria andTransactiontypeidGreaterThan(Integer value) {
            addCriterion("transactiontypeid >", value, "transactiontypeid");
            return (Criteria) this;
        }

        public Criteria andTransactiontypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("transactiontypeid >=", value, "transactiontypeid");
            return (Criteria) this;
        }

        public Criteria andTransactiontypeidLessThan(Integer value) {
            addCriterion("transactiontypeid <", value, "transactiontypeid");
            return (Criteria) this;
        }

        public Criteria andTransactiontypeidLessThanOrEqualTo(Integer value) {
            addCriterion("transactiontypeid <=", value, "transactiontypeid");
            return (Criteria) this;
        }

        public Criteria andTransactiontypeidIn(List<Integer> values) {
            addCriterion("transactiontypeid in", values, "transactiontypeid");
            return (Criteria) this;
        }

        public Criteria andTransactiontypeidNotIn(List<Integer> values) {
            addCriterion("transactiontypeid not in", values, "transactiontypeid");
            return (Criteria) this;
        }

        public Criteria andTransactiontypeidBetween(Integer value1, Integer value2) {
            addCriterion("transactiontypeid between", value1, value2, "transactiontypeid");
            return (Criteria) this;
        }

        public Criteria andTransactiontypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("transactiontypeid not between", value1, value2, "transactiontypeid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recharge_withdraw
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 15:11:02 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recharge_withdraw
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}