package com.woniu.domain;

import java.util.Date;

public class Repay {
	
	private double payAmount; //查出每期还款金额
    public double getPayAmount() {
		return payAmount;
	}

	public void setPayAmount(double payAmount) {
		this.payAmount = payAmount;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repay.repayid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer repayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repay.loanapplyid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer loanapplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repay.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer userinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repay.restamount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double restamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repay.isfinished
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Boolean isfinished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repay.repaytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Date repaytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repay.actualrepaytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Date actualrepaytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repay.isovertime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Boolean isovertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay.repayid
     *
     * @return the value of repay.repayid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getRepayid() {
        return repayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay.repayid
     *
     * @param repayid the value for repay.repayid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setRepayid(Integer repayid) {
        this.repayid = repayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay.loanapplyid
     *
     * @return the value of repay.loanapplyid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getLoanapplyid() {
        return loanapplyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay.loanapplyid
     *
     * @param loanapplyid the value for repay.loanapplyid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setLoanapplyid(Integer loanapplyid) {
        this.loanapplyid = loanapplyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay.userinfoid
     *
     * @return the value of repay.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay.userinfoid
     *
     * @param userinfoid the value for repay.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay.restamount
     *
     * @return the value of repay.restamount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getRestamount() {
        return restamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay.restamount
     *
     * @param restamount the value for repay.restamount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setRestamount(Double restamount) {
        this.restamount = restamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay.isfinished
     *
     * @return the value of repay.isfinished
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Boolean getIsfinished() {
        return isfinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay.isfinished
     *
     * @param isfinished the value for repay.isfinished
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setIsfinished(Boolean isfinished) {
        this.isfinished = isfinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay.repaytime
     *
     * @return the value of repay.repaytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Date getRepaytime() {
        return repaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay.repaytime
     *
     * @param repaytime the value for repay.repaytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setRepaytime(Date repaytime) {
        this.repaytime = repaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay.actualrepaytime
     *
     * @return the value of repay.actualrepaytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Date getActualrepaytime() {
        return actualrepaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay.actualrepaytime
     *
     * @param actualrepaytime the value for repay.actualrepaytime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setActualrepaytime(Date actualrepaytime) {
        this.actualrepaytime = actualrepaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay.isovertime
     *
     * @return the value of repay.isovertime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Boolean getIsovertime() {
        return isovertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay.isovertime
     *
     * @param isovertime the value for repay.isovertime
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setIsovertime(Boolean isovertime) {
        this.isovertime = isovertime;
    }
}