package com.woniu.domain;

public class RoletreeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roletree.roleid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roletree.treeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer treeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roletree.roleid
     *
     * @return the value of roletree.roleid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roletree.roleid
     *
     * @param roleid the value for roletree.roleid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roletree.treeid
     *
     * @return the value of roletree.treeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getTreeid() {
        return treeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roletree.treeid
     *
     * @param treeid the value for roletree.treeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setTreeid(Integer treeid) {
        this.treeid = treeid;
    }
}