package com.woniu.domain;

import java.util.ArrayList;
import java.util.List;

public class ServicechargeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public ServicechargeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andServicechargeidIsNull() {
            addCriterion("servicechargeid is null");
            return (Criteria) this;
        }

        public Criteria andServicechargeidIsNotNull() {
            addCriterion("servicechargeid is not null");
            return (Criteria) this;
        }

        public Criteria andServicechargeidEqualTo(Integer value) {
            addCriterion("servicechargeid =", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidNotEqualTo(Integer value) {
            addCriterion("servicechargeid <>", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidGreaterThan(Integer value) {
            addCriterion("servicechargeid >", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("servicechargeid >=", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidLessThan(Integer value) {
            addCriterion("servicechargeid <", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidLessThanOrEqualTo(Integer value) {
            addCriterion("servicechargeid <=", value, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidIn(List<Integer> values) {
            addCriterion("servicechargeid in", values, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidNotIn(List<Integer> values) {
            addCriterion("servicechargeid not in", values, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidBetween(Integer value1, Integer value2) {
            addCriterion("servicechargeid between", value1, value2, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicechargeidNotBetween(Integer value1, Integer value2) {
            addCriterion("servicechargeid not between", value1, value2, "servicechargeid");
            return (Criteria) this;
        }

        public Criteria andServicetypeIsNull() {
            addCriterion("servicetype is null");
            return (Criteria) this;
        }

        public Criteria andServicetypeIsNotNull() {
            addCriterion("servicetype is not null");
            return (Criteria) this;
        }

        public Criteria andServicetypeEqualTo(String value) {
            addCriterion("servicetype =", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeNotEqualTo(String value) {
            addCriterion("servicetype <>", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeGreaterThan(String value) {
            addCriterion("servicetype >", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeGreaterThanOrEqualTo(String value) {
            addCriterion("servicetype >=", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeLessThan(String value) {
            addCriterion("servicetype <", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeLessThanOrEqualTo(String value) {
            addCriterion("servicetype <=", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeLike(String value) {
            addCriterion("servicetype like", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeNotLike(String value) {
            addCriterion("servicetype not like", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeIn(List<String> values) {
            addCriterion("servicetype in", values, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeNotIn(List<String> values) {
            addCriterion("servicetype not in", values, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeBetween(String value1, String value2) {
            addCriterion("servicetype between", value1, value2, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeNotBetween(String value1, String value2) {
            addCriterion("servicetype not between", value1, value2, "servicetype");
            return (Criteria) this;
        }

        public Criteria andChargerateIsNull() {
            addCriterion("chargerate is null");
            return (Criteria) this;
        }

        public Criteria andChargerateIsNotNull() {
            addCriterion("chargerate is not null");
            return (Criteria) this;
        }

        public Criteria andChargerateEqualTo(Double value) {
            addCriterion("chargerate =", value, "chargerate");
            return (Criteria) this;
        }

        public Criteria andChargerateNotEqualTo(Double value) {
            addCriterion("chargerate <>", value, "chargerate");
            return (Criteria) this;
        }

        public Criteria andChargerateGreaterThan(Double value) {
            addCriterion("chargerate >", value, "chargerate");
            return (Criteria) this;
        }

        public Criteria andChargerateGreaterThanOrEqualTo(Double value) {
            addCriterion("chargerate >=", value, "chargerate");
            return (Criteria) this;
        }

        public Criteria andChargerateLessThan(Double value) {
            addCriterion("chargerate <", value, "chargerate");
            return (Criteria) this;
        }

        public Criteria andChargerateLessThanOrEqualTo(Double value) {
            addCriterion("chargerate <=", value, "chargerate");
            return (Criteria) this;
        }

        public Criteria andChargerateIn(List<Double> values) {
            addCriterion("chargerate in", values, "chargerate");
            return (Criteria) this;
        }

        public Criteria andChargerateNotIn(List<Double> values) {
            addCriterion("chargerate not in", values, "chargerate");
            return (Criteria) this;
        }

        public Criteria andChargerateBetween(Double value1, Double value2) {
            addCriterion("chargerate between", value1, value2, "chargerate");
            return (Criteria) this;
        }

        public Criteria andChargerateNotBetween(Double value1, Double value2) {
            addCriterion("chargerate not between", value1, value2, "chargerate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table servicecharge
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 15:11:02 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table servicecharge
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}