package com.woniu.domain;

import java.util.Date;

public class Systemlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemlog.systemlogid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer systemlogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemlog.url
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemlog.userid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemlog.time
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemlog.systemlogid
     *
     * @return the value of systemlog.systemlogid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getSystemlogid() {
        return systemlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemlog.systemlogid
     *
     * @param systemlogid the value for systemlog.systemlogid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setSystemlogid(Integer systemlogid) {
        this.systemlogid = systemlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemlog.url
     *
     * @return the value of systemlog.url
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemlog.url
     *
     * @param url the value for systemlog.url
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemlog.userid
     *
     * @return the value of systemlog.userid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemlog.userid
     *
     * @param userid the value for systemlog.userid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemlog.time
     *
     * @return the value of systemlog.time
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemlog.time
     *
     * @param time the value for systemlog.time
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}