package com.woniu.domain;

import java.util.Date;

public class Transactionlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactionlog.transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer transactionlog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactionlog.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer userinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactionlog.time
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactionlog.amount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactionlog.servicetype
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String servicetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactionlog.primarykey
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String primarykey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactionlog.transactionlog
     *
     * @return the value of transactionlog.transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getTransactionlog() {
        return transactionlog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactionlog.transactionlog
     *
     * @param transactionlog the value for transactionlog.transactionlog
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setTransactionlog(Integer transactionlog) {
        this.transactionlog = transactionlog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactionlog.userinfoid
     *
     * @return the value of transactionlog.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactionlog.userinfoid
     *
     * @param userinfoid the value for transactionlog.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactionlog.time
     *
     * @return the value of transactionlog.time
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactionlog.time
     *
     * @param time the value for transactionlog.time
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactionlog.amount
     *
     * @return the value of transactionlog.amount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactionlog.amount
     *
     * @param amount the value for transactionlog.amount
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactionlog.servicetype
     *
     * @return the value of transactionlog.servicetype
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getServicetype() {
        return servicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactionlog.servicetype
     *
     * @param servicetype the value for transactionlog.servicetype
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setServicetype(String servicetype) {
        this.servicetype = servicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactionlog.primarykey
     *
     * @return the value of transactionlog.primarykey
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getPrimarykey() {
        return primarykey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactionlog.primarykey
     *
     * @param primarykey the value for transactionlog.primarykey
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setPrimarykey(String primarykey) {
        this.primarykey = primarykey;
    }
}