package com.woniu.domain;

public class Transactiontype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactiontype.transactiontypeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer transactiontypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactiontype.transactiontypename
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String transactiontypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactiontype.url
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactiontype.transactiontypeid
     *
     * @return the value of transactiontype.transactiontypeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getTransactiontypeid() {
        return transactiontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactiontype.transactiontypeid
     *
     * @param transactiontypeid the value for transactiontype.transactiontypeid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setTransactiontypeid(Integer transactiontypeid) {
        this.transactiontypeid = transactiontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactiontype.transactiontypename
     *
     * @return the value of transactiontype.transactiontypename
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getTransactiontypename() {
        return transactiontypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactiontype.transactiontypename
     *
     * @param transactiontypename the value for transactiontype.transactiontypename
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setTransactiontypename(String transactiontypename) {
        this.transactiontypename = transactiontypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactiontype.url
     *
     * @return the value of transactiontype.url
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactiontype.url
     *
     * @param url the value for transactiontype.url
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }
}