package com.woniu.domain;

public class UserroleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.roleid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.userid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.roleid
     *
     * @return the value of userrole.roleid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.roleid
     *
     * @param roleid the value for userrole.roleid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.userid
     *
     * @return the value of userrole.userid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.userid
     *
     * @param userid the value for userrole.userid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}