package com.woniu.domain;

public class Wallet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.walletid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer walletid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.balance
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.debt
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Double debt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    private Integer userinfoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.walletid
     *
     * @return the value of wallet.walletid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getWalletid() {
        return walletid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.walletid
     *
     * @param walletid the value for wallet.walletid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setWalletid(Integer walletid) {
        this.walletid = walletid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.balance
     *
     * @return the value of wallet.balance
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.balance
     *
     * @param balance the value for wallet.balance
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.debt
     *
     * @return the value of wallet.debt
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Double getDebt() {
        return debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.debt
     *
     * @param debt the value for wallet.debt
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setDebt(Double debt) {
        this.debt = debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.userinfoid
     *
     * @return the value of wallet.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.userinfoid
     *
     * @param userinfoid the value for wallet.userinfoid
     *
     * @mbggenerated Mon Aug 19 15:11:02 CST 2019
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }
}